<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="23836" started-at="2021-01-21T16:08:26Z" finished-at="2021-01-21T16:08:50Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="23836" started-at="2021-01-21T16:08:26Z" finished-at="2021-01-21T16:08:50Z">
      <class name="com.mygithublab.LoginExcelTest">
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.mygithublab.LoginExcelTest@45c7e403]" name="initialize" is-config="true" duration-ms="15253" started-at="2021-01-21T21:38:26Z" finished-at="2021-01-21T21:38:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="loginValidFromExcelDataSS1()[pri:0, instance:com.mygithublab.LoginExcelTest@45c7e403]" name="loginValidFromExcelDataSS1" duration-ms="6171" started-at="2021-01-21T21:38:41Z" finished-at="2021-01-21T21:38:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Guru99 Bank Manager HomePage1] but found [Guru99 Bank Manager HomePage]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Guru99 Bank Manager HomePage1] but found [Guru99 Bank Manager HomePage]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.mygithublab.LoginExcelTest.loginValidFromExcelDataSS1(LoginExcelTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginValidFromExcelDataSS1 -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.mygithublab.LoginExcelTest@45c7e403]" name="closeBrowser" is-config="true" duration-ms="2373" started-at="2021-01-21T21:38:47Z" finished-at="2021-01-21T21:38:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.mygithublab.LoginExcelTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
